### ISSUE TITLE
[Feature] `user` command

### ISSUE THREAD

**Issue by Kronifer** [cat-dev-group/bot-py#76]
**What is the feature you want to add?**
A `--user` command that can grab account age, username, and profile image, similar to pydis.

**Describe the solution you'd like**
More or less the description.

**Describe alternatives you've considered**
None really.

**Would you like to implement this?**
yes

**Comment by Kronifer** [comment]
aight

**Comment by dawnofmidnight** [comment]
All issues and PRs are being closed as this repository is in the process of archival. All future development on the catbot will occur at [cat-dev-group/bot](https://github.com/cat-dev-group/bot).
